# -*- coding: utf-8 -*-
"""Dataextraction Gen_ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w0DrMAe5zE298e0ZhuXCEX1aZXRsmmnU
"""

# importing necessary libraries
import os
from pathlib import Path
import google.generativeai as genai

import warnings
warnings.filterwarnings("ignore")

# upgrading package
!pip install google-generativeai --upgrade

# reading api
gemini_api = open('gemini_api.txt','r').read()

# acessing api
import google.generativeai as genai
genai.configure(api_key=gemini_api)

"""### List available models

To see what models are available, you can use the `genai.list_models()` function.
"""

# model configurations
MODEL_CONFIG = {
  "temperature": 0.5,
  "top_p": 1,
  "top_k": 32,
  "max_output_tokens": 4096,
}

#safety settings of model
safety_settings = [
  {
    "category": "HARM_CATEGORY_HARASSMENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_HATE_SPEECH",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  },
  {
    "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
    "threshold": "BLOCK_MEDIUM_AND_ABOVE"
  }
]

# lets load gemini model with model config
model = genai.GenerativeModel(model_name = "models/gemini-3.5-flash-lite",
                              generation_config = MODEL_CONFIG,
                              safety_settings = safety_settings)

#reading image
def image_format(image_path):
  img = Path(image_path)

  if not img.exists():
    raise FileNotFoundError(f'Could not find image: {img}')

  image_parts = [
        {
            "mime_type": "image/png",
            "data": img.read_bytes()
        }
    ]
  return image_parts

# model output
def gemini_output(image_path, system_prompt, user_prompt):

    image_info = image_format(image_path)
    input_prompt= [system_prompt, image_info[0], user_prompt]
    response = model.generate_content(input_prompt)
    return response.text

system_prompt = """
               You are a specialist in comprehending receipts.
               Input images in the form of receipts will be provided to you,
               and your task is to respond to questions based on the content of the input image.
               """

image_path = r"/content/invoice (1).png"

user_prompt = "What is the invoice date?"

gemini_output(image_path, system_prompt, user_prompt)

system_prompt = """
               You are a specialist in comprehending receipts.
               Input images in the form of receipts will be provided to you,
               and your task is to respond to questions based on the content of the input image.
               """

image_path = r"/content/invoice (1).png"

user_prompt = "What is the total amount?"

gemini_output(image_path, system_prompt, user_prompt)

system_prompt = """
               You are a specialist in comprehending receipts.
               Input images in the form of receipts will be provided to you,
               and your task is to respond to questions based on the content of the input image.
               """

image_path = r"/content/invoice (1).png"

user_prompt = "What is the address of the company?"

gemini_output(image_path, system_prompt, user_prompt)

# converting invoice data to json format
system_prompt = """
               You are a specialist in comprehending receipts.
               Input images in the form of receipts will be provided to you,
               and your task is to respond to questions based on the content of the input image.
               """

image_path =  r"/content/invoice (1).png"
user_prompt = "Convert Invoice data into json format with appropriate json tags as required for the data in image "
output = gemini_output(image_path, system_prompt, user_prompt)

print(output)

# Directory for temporary uploaded files
UPLOAD_DIR = "/tmp/uploads"

os.makedirs(UPLOAD_DIR, exist_ok=True)

# Gradio function that processes the image and user prompt
def process_receipt(image,user_prompt):

    image_path = os.path.join(UPLOAD_DIR, "uploaded_receipt.png")
    image.save(image_path)
    system_prompt = """
               You are a specialist in comprehending receipts.
               Input images in the form of receipts will be provided to you,
               and your task is to respond to questions based on the content of the input image.
               """

    # Call the gemini_output function
    output = gemini_output(image_path, system_prompt, user_prompt)


    return output

pip install gradio